
apiVersion: v1
kind: Pod
metadata: 
    name: pod_apache
    labels: 
        app: apache
spec:
    containers: 
        - name: contenedor_apache
          image: httpd
          ports:
            - containerPort: 80
#    nodeName: Nodo1  FEO!!!
#    nodeSelector:    BONITO!!! PERO SIMPLON!
#        tipodisco: ssd  #etiquetas
    affinity:  # GENIAL!!!! LATAZO!!! CUIDADO !!!!
        nodeAffinity: # Afinidades a nivel de nodo
            requiredDuringSchedullingIgnoredDuringExecution:
                # Obligatorias
                nodeSelectorTerms:
                    - matchExpressions:
                        - key: tipodisco
                          values:
                            - ssd
                            - raid_ssd
                          operator: In # NotIn Exists DoesNotExists Gt Lt
            preferredDuringSchedullingIgnoredDuringExecution:
                # Deseables
                - weight: 100
                  preference:
                    matchExpressions:
                        - key: cores
                          values:
                            - 8
                            - 16
                          operator: In # NotIn Exists DoesNotExists Gt Lt
                - weight: 150
                  preference:
                    matchExpressions:
                        - key: location
                          values:
                            - aws
                          operator: In # NotIn Exists DoesNotExists Gt Lt
        podAffinity: # Afinidades a nivel de pod
            requiredDuringSchedullingIgnoredDuringExecution:
                # Obligatorias
                - labelSelector:
                    - matchExpressions:
                        - key: app
                          values:
                            - db
                          operator: In # NotIn Exists DoesNotExists Gt Lt
                  topologyKey: UBICACION # Nombre de una maquina
          podAntiAffinity: # Antiafinidades a nivel de pod
            
            
# Cluster Kubernetes
# Nodo1
    # 32Gb
# Nodo2
    # 32Gb
# Nodo3
    # 16Gb

# APPSERVER -> 2 nodos -> Nodo1, Nodo2
    # inicialmente arranca con 8 Gbs RAM
    
    
#-------
            
# Cluster Kubernetes


            # Nodo1 <- client_name: Cliente1 | hostname: Nodo1 | Ubicacion: EU
            # Nodo2 <- client_name: Cliente1 | hostname: Nodo2 | Ubicacion: EU
                #Pod1: label (app:db)
            # Nodo3 <- client_name: Cliente1 | hostname: Nodo3 | Ubicacion: EU
            # Nodo4 <- client_name: Cliente2 | hostname: Nodo4 | Ubicacion: EU
            
            
            
            # Nodo5 <- client_name: Cliente2 | hostname: Nodo5 | Ubicacion: ASIA
                #Pod2: label (app:db)
            # Nodo6 <- client_name: Cliente2 | hostname: Nodo6 | Ubicacion: ASIA
            # Nodo7 <- client_name: Cliente3 | hostname: Nodo7 | Ubicacion: ASIA
            # Nodo8 <- client_name: Cliente3 | hostname: Nodo8 | Ubicacion: ASIA
            
            
            
            # Nodo9 <- client_name: Cliente3 | hostname: Nodo9 | Ubicacion: AFRICA
    
# App1 -> Pod ( 1 nodo que me da igual, pero de cada cliente ¿?¿?¿?)
   